version: '3.1'

services:
  gradle:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    depends_on:
      - "mongo1"
      - "mongo2"
      - "mongo3"
      - "redis"


  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
#  mongo:
#    image: mongo
#    restart: always
  mongo1:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017',priority:1},{_id:1,host:'mongo2:27018',priority:0.5},{_id:2,host:'mongo3:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 30

  mongo2:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - 27018:27018


  mongo3:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    ports:
      - 27019:27019

