version: '3.1'

services:
  gradle:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
      - "redis"

  mongo:
    image: mongo
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"